### ISSUE TITLE
Schema Changes: SupplierProvisioning - Manual GR should be a STD behaviour

### ISSUE THREAD

**Issue by dsanko-sc** [OpusCapita/kanban-minsk-core-internals#14]
**Target**
Manual GR (Manual GoodReceipt booking) should be standard behavior for system. This value is configured in GormSupplierProvisioning ('supplier-editor' plugin).

**ToDo**
Set up field 'manualProdReceipt' to true value in GormSupplierProvisioning class. Update changelog correspondingly.

**Comment by asergeev-sc** [comment]
It is duplicate for https://github.com/OpusCapita/jcatalog-domain-model/issues/8
